# Generated by Django 3.2.20 on 2023-12-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0058_auto_20231201_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='status',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
