# Generated by Django 3.2.20 on 2023-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0066_auto_20231206_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_made',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
