# Generated by Django 3.2.20 on 2023-12-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0067_alter_payment_made_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_invoice',
            name='estimate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
